### ISSUE TITLE
Add wrapper LICENSE

### ISSUE THREAD

**Issue by madjokal** [JuliaBinaryWrappers/Lz4_jll.jl#1]

**Comment by giordano** [comment]
Please, don't scatter issues around these repositories, I'm probably the only one actually reading them and it's hard to track them.  Instead, open a single issue for Yggdrasil https://github.com/JuliaPackaging/Yggdrasil/issues and list all packages you find with a missing license.

**Comment by madjokal** [comment]
Sorry about that
